# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de745a3c52eb6461d31e11017a42758a77f904b978cd062b1d2c523349a755922c160916efe6dc85e0f0ff197875d88666c8214b4d8fb2325366fb994507bee4

test:
  secret_key_base: a29704315f7d9c06c44fbd874c00bb57507aeae4d1214466bf0be3ad7807b397168e7066673ebeb48069929684c66cd32c2bb1ae86480cbb76c7ca4b29e6344b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
